### ISSUE TITLE
Separate client and contract

### ISSUE THREAD

**Issue by crisgarner** [ng-es/Angular-Truffle-Dapp#4]
Right now the project has the contract and client files on the same root. I recommend adding the frontend related files to a client folder and managing two different packages.json for truffle libraries and for the client. eg:

```
.
│  README.md
│  truffle-config.js
│  package.json
│  ... solidity files
│
└───Contracts
│   │   example.sol
│   
└───Migrations
│   │  ...
│   
└───Client
    │  package.json
    │  client files
    │  ...
    └───src
         │  ...

```

**Comment by AntonioCardenas** [comment]
Fixed in commit #dc6d9e900652a316f2f30a08a8d9c69959e4edc7 Thanks for supporting
